apiVersion: v1
kind: Secret
metadata:
  name: nomad-backend-secrets
  namespace: nomad
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://user:pass@cluster.mongodb.net/NOMAD?retryWrites=true&w=majority
  CORS_ORIGIN: https://nomad.example.com
  ADMIN_API_KEY: change-me-strong-admin-key
